// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myCoreMvc.Services;

namespace myCoreMvc.Migrations
{
    [DbContext(typeof(EfCtx))]
    [Migration("20181028123332_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("myCoreMvc.Models.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Priority");

                    b.Property<string>("Reference");

                    b.Property<Guid?>("WorkPlanId");

                    b.HasKey("Id");

                    b.HasIndex("WorkPlanId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("myCoreMvc.Models.WorkPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("WorkPlans");
                });

            modelBuilder.Entity("myCoreMvc.Models.WorkItem", b =>
                {
                    b.HasOne("myCoreMvc.Models.WorkPlan", "WorkPlan")
                        .WithMany("WorkItems")
                        .HasForeignKey("WorkPlanId");
                });
#pragma warning restore 612, 618
        }
    }
}
